import os
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
load_dotenv()
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Note: GDAL/GEOS paths are OS-specific. On macOS, uncomment the following:
# GDAL_LIBRARY_PATH = '/opt/homebrew/lib/libgdal.dylib'
# GEOS_LIBRARY_PATH = '/opt/homebrew/lib/libgeos_c.dylib'
# On Windows with OSGeo4W, set paths accordingly or let Django auto-detect

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'local').lower()
_secret_key = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY')
if not _secret_key and ENVIRONMENT not in ('local', 'test', 'development'):
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set for non-local environments.')
SECRET_KEY = _secret_key or 'dev-only-insecure-secret-key-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'events',
    'rest_framework',
    'matching',
]

# Add PostGIS support when using production database
_use_postgis = bool(os.environ.get('DATABASE_URL') or os.environ.get('DATABASE_PASSWORD'))
if _use_postgis:
    INSTALLED_APPS.append('django.contrib.gis')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'users.User'

# CORS — configurable via env with local defaults
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000',
    ).split(',')
    if origin.strip()
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Local development: SQLite | PostgreSQL/PostGIS when env variables are provided
DATABASE_URL = os.environ.get('DATABASE_URL')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')

if DATABASE_URL or DATABASE_PASSWORD:
    DATABASE_NAME = os.environ.get('DATABASE_NAME', 'meetmatch')
    DATABASE_USER = os.environ.get('DATABASE_USER', 'postgres')
    DATABASE_HOST = os.environ.get('DATABASE_HOST', 'localhost')
    DATABASE_PORT = os.environ.get('DATABASE_PORT', '5432')
    _DEFAULT_DB_URL = DATABASE_URL or (
        f"postgres://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
    )

    DATABASES = {
        'default': dj_database_url.config(
            default=_DEFAULT_DB_URL,
            conn_max_age=600,
            ssl_require=(ENVIRONMENT not in ('local', 'test')),
            engine='django.contrib.gis.db.backends.postgis',  # Use PostGIS engine for geospatial support
        )
    }
else:
    # Local development: SQLite (no GDAL required)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# API Configuration
EVENTBRITE_API_KEY = os.environ.get('EVENTBRITE_API_KEY', '')
