import { StyleSheet } from 'react-native';

export const PURPLE_100 = '#f3e8ff';
export const PURPLE_200 = '#ddd6fe';
export const PURPLE_500 = '#a855f7';
export const PURPLE_700 = '#7e22ce';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PURPLE_200,
  },
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  mainContainer: {
    flex: 1,
    paddingTop: 18,
  },
  mainHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 24,
  },
  logoBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: PURPLE_500,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 20,
  },
  appTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: PURPLE_500,
    textAlign: 'center',
    marginBottom: 0,
  },
  mainWelcome: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: '600',
    color: PURPLE_700,
    textAlign: 'center',
  },
  card: {
    backgroundColor: PURPLE_500,
    borderRadius: 12,
    padding: 16,
    gap: 10,
    width: '100%',
    maxWidth: 400,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: PURPLE_100,
  },
  subtitleBold: {
    fontWeight: '700',
    color: '#ffffff',
  },
  sectionHeading: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  input: {
    borderWidth: 1,
    borderColor: PURPLE_500,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: '#ffffff',
    color: '#000000',
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  inputHalf: {
    flex: 1,
    borderWidth: 1,
    borderColor: PURPLE_500,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: '#ffffff',
    color: '#000000',
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PURPLE_500,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#000000',
    backgroundColor: '#ffffff',
  },
  passwordToggle: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: PURPLE_100,
  },
  passwordToggleText: {
    color: PURPLE_700,
    fontWeight: '700',
    fontSize: 13,
  },
  primaryButton: {
    marginTop: 4,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    opacity: 1,
  },
  primaryButtonPressed: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: PURPLE_500,
    fontWeight: '600',
    fontSize: 16,
  },
  linkText: {
    color: PURPLE_100,
    textAlign: 'center',
    marginTop: 8,
  },
  linkButton: {
    marginTop: 12,
  },
  errorText: {
    color: '#ffffff',
    marginTop: 4,
    textAlign: 'center',
  },
  successText: {
    color: '#ffffff',
    marginTop: 4,
    textAlign: 'center',
  },
  mainPages: {
    flex: 1,
  },
  mainPagesContent: {
    alignItems: 'stretch',
    flexGrow: 1,
  },
  mainPage: {
    flex: 1,
    paddingHorizontal: 16,
  },
  mainPageScroll: {
    flex: 1,
  },
  mainPageScrollContent: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  mainCard: {
    flexGrow: 1,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 18,
    minHeight: 420,
    borderWidth: 1,
    borderColor: PURPLE_100,
  },
  mainCardTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: PURPLE_700,
    marginBottom: 8,
  },
  mainCardText: {
    fontSize: 15,
    color: '#5b5670',
    marginBottom: 16,
  },
  mainList: {
    gap: 12,
  },
  mainListItem: {
    backgroundColor: PURPLE_100,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  mainListTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: PURPLE_700,
    marginBottom: 4,
  },
  mainListText: {
    fontSize: 14,
    color: '#4b5563',
  },
  eventFeed: {
    gap: 14,
  },
  eventCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PURPLE_200,
    padding: 14,
    gap: 12,
    shadowColor: '#0f172a',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  eventHeroRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  eventDateBadge: {
    width: 58,
    borderRadius: 14,
    backgroundColor: PURPLE_100,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  eventDateMonth: {
    fontSize: 11,
    fontWeight: '800',
    color: PURPLE_500,
    letterSpacing: 0.6,
  },
  eventDateDay: {
    fontSize: 22,
    fontWeight: '800',
    color: PURPLE_700,
    marginTop: 2,
  },
  eventHeroContent: {
    flex: 1,
    gap: 4,
  },
  eventTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  eventTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    color: '#1f2937',
  },
  eventSourcePill: {
    backgroundColor: PURPLE_100,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  eventSourceText: {
    color: PURPLE_700,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  eventMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  eventEmoji: {
    fontSize: 15,
  },
  eventMetaText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '600',
  },
  eventMetaSubtext: {
    color: '#6b7280',
    fontSize: 12,
  },
  eventDescription: {
    color: '#4b5563',
    fontSize: 14,
    lineHeight: 20,
  },
  eventChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  eventChip: {
    backgroundColor: '#f5f3ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eventChipText: {
    color: PURPLE_700,
    fontSize: 12,
    fontWeight: '600',
  },
  eventFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 4,
  },
  eventFooterText: {
    color: '#6b7280',
    fontSize: 12,
  },
  eventFooterLink: {
    color: PURPLE_500,
    fontSize: 13,
    fontWeight: '700',
  },
  profileRow: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE_100,
  },
  profileLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PURPLE_500,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  profileValue: {
    fontSize: 16,
    color: '#1f2937',
  },
  profileInput: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  profileHint: {
    marginTop: 6,
    fontSize: 12,
    color: '#6b7280',
  },
  profileSuccess: {
    marginTop: 8,
    textAlign: 'center',
    color: PURPLE_700,
    fontWeight: '600',
  },
  secondaryButton: {
    marginTop: 10,
    backgroundColor: PURPLE_100,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: PURPLE_700,
    fontWeight: '600',
    fontSize: 16,
  },
  logoutButton: {
    marginTop: 10,
    backgroundColor: PURPLE_500,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PURPLE_500,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  bottomNav: {
    flexDirection: 'row',
    marginTop: 16,
    marginHorizontal: 16,
    marginBottom: 18,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 8,
    gap: 8,
  },
  navItem: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  navItemActive: {
    backgroundColor: PURPLE_500,
  },
  navText: {
    color: PURPLE_500,
    fontWeight: '600',
  },
  navTextActive: {
    color: '#ffffff',
  },
  pillContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#ffffff',
  },
  pillSelected: {
    backgroundColor: PURPLE_100,
    borderColor: PURPLE_500,
  },
  pillText: {
    color: '#000000',
  },
  pillTextSelected: {
    color: PURPLE_500,
    fontWeight: '600',
  },
  topPillSelected: {
    backgroundColor: PURPLE_100,
    borderColor: PURPLE_500,
  },
  topPillTextSelected: {
    color: PURPLE_700,
    fontWeight: '700',
  },
  chatThreadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: PURPLE_100,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  chatThreadAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatThreadAvatarImage: {
    width: '100%',
    height: '100%',
  },
  chatThreadAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: PURPLE_700,
  },
  chatThreadInfo: {
    flex: 1,
  },
  chatChevron: {
    fontSize: 24,
    color: PURPLE_700,
    fontWeight: '700',
  },
  chatBackButton: {
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  chatBackText: {
    color: PURPLE_700,
    fontWeight: '700',
  },
  chatThreadName: {
    fontSize: 20,
    fontWeight: '700',
    color: PURPLE_700,
    marginBottom: 12,
  },
  chatMessages: {
    gap: 10,
  },
  chatBubble: {
    maxWidth: '86%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  chatBubbleYou: {
    alignSelf: 'flex-end',
    backgroundColor: PURPLE_500,
  },
  chatBubbleThem: {
    alignSelf: 'flex-start',
    backgroundColor: PURPLE_100,
  },
  chatBubbleTextYou: {
    color: '#ffffff',
    fontSize: 15,
  },
  chatBubbleTextThem: {
    color: '#1f2937',
    fontSize: 15,
  },
  chatMetaText: {
    marginTop: 4,
    fontSize: 11,
  },
  chatMetaTextYou: {
    color: '#ede9fe',
    textAlign: 'right',
  },
  chatMetaTextThem: {
    color: '#6b7280',
  },
  chatComposer: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    alignItems: 'center',
  },
  chatComposerInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  chatSendButton: {
    backgroundColor: PURPLE_500,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  chatSendButtonDisabled: {
    opacity: 0.45,
  },
  chatSendButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  matchCounter: {
    fontSize: 13,
    color: PURPLE_500,
    fontWeight: '700',
    marginBottom: 6,
  },
  matchNotice: {
    color: '#4b5563',
    marginBottom: 12,
  },
  swipeDeck: {
    height: 470,
    marginBottom: 18,
  },
  matchCard: {
    position: 'absolute',
    width: '100%',
    height: 450,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: PURPLE_100,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  matchCardTop: {
    top: 0,
  },
  matchCardStacked: {
    opacity: 0.92,
  },
  matchCardImage: {
    width: '100%',
    height: 250,
    backgroundColor: PURPLE_100,
  },
  matchCardBody: {
    flex: 1,
    padding: 16,
    gap: 10,
  },
  matchHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  matchName: {
    fontSize: 24,
    fontWeight: '700',
    color: PURPLE_700,
  },
  matchMeta: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 2,
  },
  matchReason: {
    flexShrink: 1,
    fontSize: 12,
    color: PURPLE_500,
    fontWeight: '700',
    textAlign: 'right',
  },
  matchBio: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 21,
  },
  matchPrompt: {
    fontSize: 14,
    color: PURPLE_700,
    fontWeight: '600',
  },
  matchChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  matchChip: {
    backgroundColor: PURPLE_100,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  matchChipText: {
    color: PURPLE_700,
    fontWeight: '600',
    fontSize: 12,
  },
  matchBadge: {
    position: 'absolute',
    top: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 2,
    borderRadius: 12,
    zIndex: 5,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  matchBadgeLike: {
    right: 18,
    borderColor: '#16a34a',
    transform: [{ rotate: '10deg' }],
  },
  matchBadgePass: {
    left: 18,
    borderColor: '#dc2626',
    transform: [{ rotate: '-10deg' }],
  },
  matchBadgeText: {
    fontSize: 16,
    fontWeight: '800',
    color: PURPLE_700,
  },
  matchActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  matchActionButton: {
    width: 92,
    height: 78,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  matchActionPass: {
    backgroundColor: '#fff1f2',
    borderColor: '#fecdd3',
  },
  matchActionLike: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
  },
  matchActionEmoji: {
    fontSize: 28,
    marginBottom: 4,
  },
  matchActionLabel: {
    fontWeight: '700',
    color: PURPLE_700,
  },
  matchEmptyState: {
    backgroundColor: PURPLE_100,
    borderRadius: 18,
    padding: 18,
    gap: 10,
  },
  matchEmptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: PURPLE_700,
  },
});
