import { StyleSheet } from 'react-native';



// Pure lavender gradient colors (light, pure lavender)
export const LIGHT_PURPLE_GRADIENT_START = '#ede7f6'; // light pure lavender start
export const LIGHT_PURPLE_GRADIENT_END = '#f3eaff';   // light pure lavender end
export const LIGHT_PURPLE_SOLID = '#f6f2fa';          // solid light lavender

// Deeper pink accent colors
export const LIGHT_PINK = '#e75480'; // deeper pink
export const LIGHT_PINK_ALT = '#d72660'; // even deeper pink for alt
export const BLUSH_PINK = '#f0ecff'; // pale lavender end-stop (pure lavender)

// Restore original purple color constants for compatibility
export const PURPLE_100 = '#f3f0ff';
export const PURPLE_200 = '#ddd6fe';
export const PURPLE_500 = '#06B6D4';
export const PURPLE_700 = '#0f3f4a';

const PINK_500 = '#A855F7';
// Removed teal/mint/gold constants
const SURFACE = '#ffffff';
const TEXT_MUTED = '#5f6f76';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: LIGHT_PURPLE_SOLID,
  },
  screenGradient: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 24,
    backgroundColor: LIGHT_PURPLE_SOLID,
  },
  containerTransparent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 24,
    backgroundColor: 'transparent',
  },
  mainContainer: {
    flex: 1,
    paddingTop: 12,
    backgroundColor: LIGHT_PURPLE_SOLID,
  },
  mainContainerTransparent: {
    backgroundColor: 'transparent',
  },
  mainHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 12,
  },
  headerTable: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  headerMiddle: {
    flex: 1,
  },
  headerGreeting: {
    fontSize: 24,
    fontWeight: '800',
    color: PURPLE_700,
  },
  headerSubtext: {
    marginTop: 2,
    fontSize: 12,
    color: TEXT_MUTED,
    textAlign: 'center',
  },
  notificationButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationIcon: {
    fontSize: 20,
    color: LIGHT_PINK,
  },
  notificationBadge: {
    position: 'absolute',
    top: 5,
    right: 4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: LIGHT_PINK,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  notificationBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 8,
  },
  mainBrandRow: {
    justifyContent: 'flex-start',
    marginBottom: 0,
  },
  logoBadge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  logoText: {
    fontSize: 20,
  },
  appTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: PURPLE_700,
    textAlign: 'center',
    marginBottom: 0,
    letterSpacing: -0.4,
  },
  mainWelcome: {
    fontSize: 16,
    fontWeight: '700',
    color: PURPLE_700,
    textAlign: 'left',
  },
  homeHeroCard: {
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  homeHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  homeHeroBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#f5f3ff',
  },
  homeHeroBadgeText: {
    color: PINK_500,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  homeHeroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: PURPLE_700,
  },
  homeHeroText: {
    fontSize: 14,
    color: TEXT_MUTED,
    lineHeight: 20,
  },
  authShell: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 24,
    padding: 18,
    gap: 12,
    width: '100%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  gradientCard: {
    borderRadius: 24,
    padding: 18,
    gap: 12,
    width: '100%',
    maxWidth: 420,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: PURPLE_500,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  softGradientCard: {
    borderColor: 'rgba(6, 182, 212, 0.12)',
    backgroundColor: 'rgba(255,255,255,0.92)', // more white, semi-transparent
    shadowColor: LIGHT_PINK,
  },
  loginGradientCard: {
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(255,255,255,0.92)', // more white, semi-transparent
    shadowColor: LIGHT_PINK,
  },
    signupTitle: {
      color: LIGHT_PINK,
      fontWeight: '700',
    },
  loginCard: {
    backgroundColor: LIGHT_PINK,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
    signupPrimaryButtonText: {
      color: '#fff',
    },
  loginTitle: {
    color: PURPLE_700,
  },
  loginFieldLabel: {
    color: PURPLE_700,
  },
  loginInput: {
    borderColor: LIGHT_PINK,
    backgroundColor: '#fff',
    color: PURPLE_700,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  loginPasswordRow: {
    borderColor: LIGHT_PINK,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
  },
  loginPasswordInput: {
    color: PURPLE_700,
    backgroundColor: '#fff',
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  loginPasswordToggle: {
    backgroundColor: LIGHT_PINK,
    borderRadius: 8,
    height: 47,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPasswordToggleText: {
    color: '#fff',
    fontWeight: '700',
  },
  loginPrimaryButton: {
    backgroundColor: LIGHT_PINK,
    shadowColor: LIGHT_PINK,
  },
  loginPrimaryButtonText: {
    color: '#fff',
  },
  loginFooterText: {
    color: PURPLE_700,
  },
  loginSignupLink: {
    color: LIGHT_PINK,
  },
  loginSecondaryLink: {
    color: LIGHT_PINK,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    color: PINK_500,
    textTransform: 'uppercase',
  },
  heroPanel: {
    backgroundColor: '#f0fbff',
    borderRadius: 24,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.12)',
  },
  heroPanelAlt: {
    backgroundColor: '#f0fdf8',
    borderRadius: 24,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.28)',
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: PURPLE_700,
    lineHeight: 30,
  },
  heroPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.18)',
  },
  heroPillText: {
    color: PURPLE_700,
    fontWeight: '700',
    fontSize: 12,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: PURPLE_700,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: TEXT_MUTED,
    lineHeight: 20,
  },
  subtitleBold: {
    fontWeight: '800',
    color: PURPLE_700,
  },
  sectionHeading: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: '700',
    color: PURPLE_700,
  },
  helperText: {
    fontSize: 12,
    color: TEXT_MUTED,
    lineHeight: 18,
  },
  fieldGroup: {
    gap: 6,
  },
  fieldGroupHalf: {
    flex: 1,
    gap: 6,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: PURPLE_700,
  },
  input: {
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    color: PURPLE_700,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  inputHalf: {
    flex: 1,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    color: PURPLE_700,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    borderRadius: 14,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: PURPLE_700,
    backgroundColor: '#fff',
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  passwordToggle: {
    paddingHorizontal: 12,
    paddingVertical: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: LIGHT_PINK,
    height: 47,
    borderRadius:0,
  },
  passwordToggleText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  primaryButton: {
    marginTop: 4,
    backgroundColor: LIGHT_PINK,
    color: '#fff',
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
    opacity: 1,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  primaryButtonPressed: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  linkText: {
    color: LIGHT_PINK,
    textAlign: 'center',
    marginTop: 4,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  linkButton: {
    marginTop: 4,
  },
  footerRow: {
    alignItems: 'center',
    gap: 6,
  },
  footerInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    flexWrap: 'wrap',
  },
  footerText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  errorText: {
    color: '#be123c',
    marginTop: 4,
    textAlign: 'center',
    backgroundColor: '#fff1f4',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    fontWeight: '600',
  },
  successText: {
    color: '#18794e',
    marginTop: 4,
    textAlign: 'center',
    backgroundColor: '#eefbf3',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    fontWeight: '600',
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryPill: {
    flex: 1,
    minWidth: 92,
    backgroundColor: PURPLE_100,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.14)',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '800',
    color: PURPLE_700,
  },
  summaryLabel: {
    fontSize: 12,
    color: TEXT_MUTED,
    marginTop: 2,
  },
  mainPages: {
    flex: 1,
  },
  mainPagesContent: {
    alignItems: 'stretch',
    flexGrow: 1,
  },
  mainPage: {
    flex: 1,
    paddingHorizontal: 16,
  },
  mainPageScroll: {
    flex: 1,
  },
  mainPageScrollContent: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  mainCard: {
    flexGrow: 1,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 24,
    padding: 18,
    minHeight: 420,
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.24)',
    shadowColor: PURPLE_500,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  mainCardTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: PURPLE_700,
    marginBottom: 8,
  },
  mainCardText: {
    fontSize: 15,
    color: '#5b5670',
    marginBottom: 16,
    lineHeight: 21,
  },
  eventHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  eventHeaderTextBlock: {
    flex: 1,
  },
  eventFilterMenuButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: PURPLE_200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventFilterMenuIcon: {
    color: PURPLE_700,
    fontSize: 18,
    fontWeight: '700',
  },
  mainList: {
    gap: 12,
  },
  mainListItem: {
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
  },
  mainListTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: PURPLE_700,
    marginBottom: 4,
  },
  mainListText: {
    fontSize: 14,
    color: '#4b5563',
  },
  eventSearchInput: {
    borderWidth: 0,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    color: '#111827',
    marginBottom: 8,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  eventFilterPopup: {
    backgroundColor: '#fffaf2',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: PURPLE_200,
    gap: 12,
    shadowColor: PURPLE_500,
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  eventFilterPopupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  eventFilterPopupTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: PURPLE_700,
  },
  eventFilterPopupClose: {
    fontSize: 16,
    fontWeight: '700',
    color: PURPLE_700,
  },
  eventFilterRow: {
    marginBottom: 2,
    gap: 8,
  },
  eventFilterLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PURPLE_700,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  eventRadiusFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  eventRadiusInput: {
    flex: 0,
    width: 96,
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  eventRadiusSuffix: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4b5563',
  },
  eventInterestScrollArea: {
    maxHeight: 160,
  },
  eventInterestFilterWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 4,
  },
  eventInterestFilterRow: {
    gap: 8,
    paddingBottom: 8,
  },
  eventInterestFilterChip: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PURPLE_200,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  eventInterestFilterChipActive: {
    backgroundColor: LIGHT_PINK,
    borderColor: LIGHT_PINK,
  },
  eventInterestFilterText: {
    color: PURPLE_700,
    fontSize: 12,
    fontWeight: '600',
  },
  eventInterestFilterTextActive: {
    color: '#ffffff',
  },
  eventSearchMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 12,
  },
  eventSearchEmptyState: {
    backgroundColor: PURPLE_100,
    borderRadius: 16,
    padding: 16,
    gap: 8,
  },
  eventFeed: {
    gap: 14,
  },
  eventCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    borderRadius: 18,
    borderWidth: 0,
    padding: 14,
    gap: 12,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  eventHeroRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  eventDateBadge: {
    width: 58,
    borderRadius: 14,
    backgroundColor: PURPLE_100,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  eventDateMonth: {
    fontSize: 11,
    fontWeight: '800',
    color: LIGHT_PINK,
    letterSpacing: 0.6,
  },
  eventDateDay: {
    fontSize: 22,
    fontWeight: '800',
    color: PURPLE_700,
    marginTop: 2,
  },
  eventHeroContent: {
    flex: 1,
    gap: 4,
  },
  eventTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  eventTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    color: '#1f2937',
  },
  eventSourcePill: {
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  eventSourceText: {
    color: PURPLE_700,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  eventMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  eventEmoji: {
    fontSize: 15,
  },
  eventMetaText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '600',
  },
  eventMetaSubtext: {
    color: '#6b7280',
    fontSize: 12,
  },
  eventDescription: {
    color: '#4b5563',
    fontSize: 14,
    lineHeight: 20,
  },
  eventChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  eventChip: {
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eventChipText: {
    color: PURPLE_700,
    fontSize: 12,
    fontWeight: '600',
  },
  eventMatchContext: {
    gap: 8,
  },
  eventMatchLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PURPLE_700,
  },
  eventMatchChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  eventMatchChip: {
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.55)',
  },
  eventMatchChipText: {
    color: PURPLE_700,
    fontSize: 12,
    fontWeight: '600',
  },
  eventFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 4,
  },
  eventFooterMeta: {
    flex: 1,
    gap: 4,
  },
  eventFooterText: {
    color: '#6b7280',
    fontSize: 12,
  },
  eventFooterLink: {
    color: LIGHT_PINK,
    fontSize: 13,
    fontWeight: '700',
  },
  eventInterestButton: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  eventInterestButtonActive: {
    backgroundColor: LIGHT_PINK,
    borderColor: LIGHT_PINK,
  },
  eventInterestButtonText: {
    color: PURPLE_700,
    fontSize: 12,
    fontWeight: '700',
  },
  eventInterestButtonTextActive: {
    color: '#ffffff',
  },
  profileRow: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: PURPLE_100,
  },
  profileLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: LIGHT_PINK,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  profileValue: {
    fontSize: 16,
    color: '#1f2937',
  },
  profileInput: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  profileHint: {
    marginTop: 6,
    fontSize: 12,
    color: '#6b7280',
  },
  profileSuccess: {
    marginTop: 8,
    textAlign: 'center',
    color: PURPLE_700,
    fontWeight: '600',
  },
  profileHistorySection: {
    marginBottom: 12,
    gap: 14,
  },
  historyLinkCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: LIGHT_PURPLE_SOLID,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
  },
  historyLinkCardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    backgroundColor: LIGHT_PURPLE_SOLID, // unified lavender background
  },
  historyLinkMatchedLabel: {
    color: LIGHT_PINK_ALT,
  },
  historyLinkBody: {
    flex: 1,
    gap: 4,
  },
  historyLinkMeta: {
    fontSize: 13,
    color: '#6b7280',
    lineHeight: 18,
  },
  historyLinkArrow: {
    fontSize: 24,
    fontWeight: '700',
    color: LIGHT_PINK_ALT,
  },
  historySearchInput: {
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
    color: LIGHT_PINK, // pink text for input
    // placeholderTextColor must be set in the component, not here
  },
  historyToggleRow: {
    flexDirection: 'row',
    gap: 6,
    padding: 4,
    borderRadius: 14,
    backgroundColor: 'rgba(231, 84, 128, 0.10)', // faded LIGHT_PINK
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  historyToggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyToggleButtonActive: {
    backgroundColor: LIGHT_PINK,
    borderColor: LIGHT_PINK,
  },
  historyToggleText: {
    fontSize: 13,
    fontWeight: '700',
  },
  historyToggleTextActive: {
    color: '#ffffff',
  },
  profileHistoryGroup: {
    gap: 8,
  },
  profileHistoryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: PURPLE_700,
  },
  profileHistoryLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: PINK_500,
  },
  profileHistoryList: {
    gap: 8,
  },
  profileHistoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'transparent',
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  profileHistoryAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ffffff',
  },
  profileHistoryEventIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  profileHistoryEventIconText: {
    fontSize: 18,
  },
  profileHistoryCardBody: {
    flex: 1,
  },
  profileHistoryCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2937',
  },
  profileHistoryCardMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#6b7280',
  },
  profileHistoryEmpty: {
    fontSize: 13,
    color: '#6b7280',
    lineHeight: 18,
  },
  secondaryButton: {
    marginTop: 10,
    backgroundColor: LIGHT_PINK,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
    borderWidth: 0,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  secondaryButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  logoutButton: {
    marginTop: 10,
    backgroundColor: LIGHT_PINK_ALT,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: LIGHT_PINK,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  bottomNav: {
    flexDirection: 'row',
    marginTop: 14,
    marginHorizontal: 16,
    marginBottom: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 22,
    padding: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: LIGHT_PINK,
    shadowColor: LIGHT_PINK,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  navItem: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  navItemActive: {
    backgroundColor: LIGHT_PINK,
    color: '#ffffff',
  },
  navText: {
    color: LIGHT_PINK,
    fontWeight: '700',
    fontSize: 12,
  },
  navTextActive: {
    color: '#fff',
  },
  pillContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#ffffff',
  },
  pillSelected: {
    backgroundColor: LIGHT_PINK,
    borderColor: LIGHT_PINK,
  },
  pillText: {
    color: '#000000',
  },
  pillTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  topPillSelected: {
    backgroundColor: LIGHT_PINK,
    borderColor: LIGHT_PINK,
  },
  topPillTextSelected: {
    color: '#fff',
    fontWeight: '700',
  },
  chatThreadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: PURPLE_100,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: PURPLE_200,
  },
  chatThreadAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatThreadAvatarImage: {
    width: '100%',
    height: '100%',
  },
  chatThreadAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: PURPLE_700,
  },
  chatThreadInfo: {
    flex: 1,
  },
  chatChevron: {
    fontSize: 24,
    color: PURPLE_700,
    fontWeight: '700',
  },
  chatBackButton: {
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  chatBackText: {
    color: PURPLE_700,
    fontWeight: '700',
  },
  chatThreadName: {
    fontSize: 20,
    fontWeight: '700',
    color: PURPLE_700,
    marginBottom: 12,
  },
  chatMessages: {
    gap: 10,
  },
  chatBubble: {
    maxWidth: '86%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  chatBubbleYou: {
    alignSelf: 'flex-end',
    backgroundColor: LIGHT_PINK,
  },
  chatBubbleThem: {
    alignSelf: 'flex-start',
    backgroundColor: '#f9d0e3',
  },
  chatBubbleTextYou: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  chatBubbleTextThem: {
    color: '#b03060',
    fontSize: 15,
  },
  chatMetaText: {
    marginTop: 4,
    fontSize: 11,
  },
  chatMetaTextYou: {
    color: '#d9fbff',
    textAlign: 'right',
  },
  chatMetaTextThem: {
    color: '#6b7280',
  },
  chatComposer: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    alignItems: 'center',
  },
  chatComposerInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: PURPLE_200,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  chatSendButton: {
    backgroundColor: LIGHT_PINK,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  chatSendButtonDisabled: {
    opacity: 0.45,
  },
  chatSendButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  matchCounter: {
    fontSize: 13,
    color: LIGHT_PINK,
    fontWeight: '700',
    marginBottom: 6,
  },
  matchNotice: {
    color: '#4b5563',
    marginBottom: 12,
  },
  swipeDeck: {
    height: 500,
    marginBottom: 18,
  },
  matchCard: {
    position: 'absolute',
    width: '100%',
    height: 480,
    backgroundColor: '#fff',
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 0,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  matchCardTop: {
    top: 0,
  },
  matchCardStacked: {
    opacity: 0.92,
  },
  matchCardImage: {
    width: '100%',
    height: 220,
    backgroundColor: '#f3f0ff',
  },
  matchCardBody: {
    flex: 1,
    padding: 14,
    gap: 8,
  },
  matchHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  matchName: {
    fontSize: 24,
    fontWeight: '700',
    color: PURPLE_700,
  },
  matchMeta: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 2,
  },
  matchReason: {
    flexShrink: 1,
    fontSize: 12,
    color: LIGHT_PINK,
    fontWeight: '700',
    textAlign: 'right',
  },
  matchBio: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 21,
  },
  matchPrompt: {
    fontSize: 14,
    color: PURPLE_700,
    fontWeight: '600',
  },
  matchSharedEventsBox: {
    backgroundColor: 'transparent',
    borderRadius: 14,
    padding: 10,
    gap: 8,
  },
  matchSharedEventsLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: PURPLE_700,
    lineHeight: 16,
    flexShrink: 1,
  },
  matchSharedEventsHint: {
    fontSize: 12,
    color: '#6b7280',
    lineHeight: 18,
  },
  matchChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  matchChip: {
    backgroundColor: '#f3f0ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: '100%',
  },
  matchChipText: {
    color: PURPLE_700,
    fontWeight: '600',
    fontSize: 12,
    flexShrink: 1,
  },
  matchBadge: {
    position: 'absolute',
    top: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 2,
    borderRadius: 12,
    zIndex: 5,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  matchBadgeLike: {
    right: 18,
    borderColor: LIGHT_PINK,
    transform: [{ rotate: '10deg' }],
  },
  matchBadgePass: {
    left: 18,
    borderColor: PURPLE_500,
    transform: [{ rotate: '-10deg' }],
  },
  matchBadgeText: {
    fontSize: 16,
    fontWeight: '800',
    color: PURPLE_700,
  },
  matchActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  matchActionButton: {
    width: 92,
    height: 78,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  matchActionPass: {
    backgroundColor: '#fff1f7',
    borderColor: '#f6bfdc',
  },
  matchActionLike: {
    backgroundColor: '#f0fdf8',
    borderColor: 'rgba(110, 231, 183, 0.45)',
  },
  matchActionEmoji: {
    fontSize: 28,
    marginBottom: 4,
  },
  matchActionLabel: {
    fontWeight: '700',
    color: PURPLE_700,
  },
  matchEmptyState: {
    backgroundColor: PURPLE_100,
    borderRadius: 18,
    padding: 18,
    gap: 10,
  },
  matchEmptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: PURPLE_700,
  },
  profileHistorySeparator: {
    height: 1,
    backgroundColor: 'rgba(60,60,60,0.08)',
    marginVertical: 4,
    width: '100%',
  },
});
