# Generated by Django 6.0.3 on 2026-03-17 21:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('eventbrite_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ticketmaster_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('source', models.CharField(choices=[('eventbrite', 'Eventbrite'), ('ticketmaster', 'Ticketmaster'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('external_data', models.JSONField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
